export const SITE_INFO = {
    title: "Portfolio Web - Nicolás Rozas",
    fullName: "Nicolás Andrés Rozas Pizarro",
    shortName: "Nicolás Rozas",
    role1: "Developer Full Stack",
    level1: "Junior",
    role2: "Data Analyst",
    level2: "Junior",
    description: "Portafolio de Nicolás Rozas, Analista Programador Computacional. Desarrollo aplicaciones web y móviles con Astro, React, Node.js y Supabase.",
    url: "https://portfolio-web-nico-rozas-dev.netlify.app",
    whatsapp: "https://wa.me/+56976987925",
    currentYear: new Date().getFullYear(),
    location: "Santiago, Chile",
    ogImage: "/og-image.webp",
}